### ISSUE TITLE
v0.2.3 says php: >=5.3.0, but it's not compatible with PHP 5.6

### ISSUE THREAD

**Issue by kenorb** [corbanb/freebird-php#9]
According to [requires of v0.2.3](https://packagist.org/packages/corbanb/freebird-php#v0.2.3), the code should be compatible with PHP 5.6, but it's not, since it's using [`symfony/event-dispatcher`](https://packagist.org/packages/symfony/event-dispatcher) package, which requires PHP `^7.1.3`.

Reproducible steps:

```
$ composer require corbanb/freebird-php:~0.2.2
$ composer show
corbanb/freebird-php     v0.2.3 Twitter API v1.1 Application only authoization library
symfony/event-dispatcher v4.0.3 Symfony EventDispatcher Component
guzzle/guzzle            v3.8.1 Guzzle is a PHP HTTP client library and framew...
$ find vendor/symfony/event-dispatcher -name \*.php -exec php56 -l {} ';'
...
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php on line 34
Fatal error: Default value for parameters with a class type hint can only be NULL in vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php on line 34
Errors parsing vendor/symfony/event-dispatcher/DependencyInjection/RegisterListenersPass.php
...
```

<sup>Note: The `php56` command is a link pointing to PHP 5.6 binary.</sup>

**Comment by corbanb** [comment]
@kenorb sorry about that. I haven't updated this package in quite sometime or kept up with it. If you'd like to submit a PR please do so and I will merge it in. 

This was last worked on in July of 2015.

**Comment by kenorb** [comment]
Thanks for the reply. I've checked and I think the right place to fix is in [`guzzle/guzzle`](https://packagist.org/packages/guzzle/guzzle) package, since this one doesn't require `symfony/event-dispatcher` directly. Actually `guzzle/guzzle` states that it can work with PHP >=5.3.3, but it's fetching `symfony/event-dispatcher` package which requires PHP7.1. So this should be fixed in the `guzzle/guzzle3` repository. I've created the issue at guzzle/guzzle3/issues/88, so I'll close this one then.

**Comment by corbanb** [comment]
@kenorb thanks. I hope it all works out. This package seems to stay alive and works well for most people still using it. Best of luck.

**Comment by kenorb** [comment]
I've solved it by the following workaround which overrides `symfony/event-dispatcher` package to the version which is compatible with PHP 5.6:

```
{
    "require": {
        "corbanb/freebird-php": "~0.2.2"
    },
    "require-dev": {
        "symfony/event-dispatcher": "3.4.3"
    }
}
```

And it looks like it works.
